### ISSUE TITLE
Add MIT license

### ISSUE THREAD

**Issue by pedro-teixeira** [pedro-teixeira/grid-bundle#9]

**Comment by admin-qqq** [comment]
@pedro-teixeira nice grid bundle, thanks!! :+1:

**Comment by pedro-teixeira** [comment]
You are welcome @admin-qqq!

**Comment by AveVlad** [comment]
@pedro-teixeira Thanks for your bundle! :+1: :clap:

**Comment by pedro-teixeira** [comment]
You are also welcome @AveVlad!
